"""init

Revision ID: feb8e14d7de4
Revises: 
Create Date: 2026-03-25 08:10:48.605704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feb8e14d7de4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplement_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('standard_dosage', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('target_goal', sa.String(length=20), nullable=True),
    sa.Column('benefits', sa.Text(), nullable=True),
    sa.Column('recommended_for_activity', sa.String(length=50), nullable=True),
    sa.Column('is_global', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_supplement_catalog_id'), 'supplement_catalog', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('daily_calorie_target', sa.Integer(), nullable=True),
    sa.Column('protein_target_g', sa.Float(), nullable=True),
    sa.Column('carbs_target_g', sa.Float(), nullable=True),
    sa.Column('fats_target_g', sa.Float(), nullable=True),
    sa.Column('goal_weight_lbs', sa.Float(), nullable=True),
    sa.Column('current_weight_lbs', sa.Float(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('body_fat_pct', sa.Float(), nullable=True),
    sa.Column('activity_level', sa.String(length=50), nullable=True),
    sa.Column('primary_goal', sa.String(length=50), nullable=True),
    sa.Column('preferred_unit', sa.String(length=20), nullable=True),
    sa.Column('theme_mode', sa.String(length=20), nullable=True),
    sa.Column('theme_accent', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_pro_user', sa.Boolean(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=True),
    sa.Column('subscription_end_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('chat_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_history_id'), 'chat_history', ['id'], unique=False)
    op.create_index(op.f('ix_chat_history_user_id'), 'chat_history', ['user_id'], unique=False)
    op.create_table('daily_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weight_lbs', sa.Float(), nullable=True),
    sa.Column('is_refeed_day', sa.Boolean(), nullable=True),
    sa.Column('is_rest_day', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('calorie_target_override', sa.Integer(), nullable=True),
    sa.Column('protein_target_override', sa.Float(), nullable=True),
    sa.Column('carbs_target_override', sa.Float(), nullable=True),
    sa.Column('fats_target_override', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_logs_date'), 'daily_logs', ['date'], unique=False)
    op.create_index(op.f('ix_daily_logs_id'), 'daily_logs', ['id'], unique=False)
    op.create_index(op.f('ix_daily_logs_is_refeed_day'), 'daily_logs', ['is_refeed_day'], unique=False)
    op.create_index(op.f('ix_daily_logs_user_id'), 'daily_logs', ['user_id'], unique=False)
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_ar', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('calories_per_100g', sa.Float(), nullable=False),
    sa.Column('protein_per_100g', sa.Float(), nullable=False),
    sa.Column('carbs_per_100g', sa.Float(), nullable=False),
    sa.Column('fats_per_100g', sa.Float(), nullable=False),
    sa.Column('fiber_per_100g', sa.Float(), nullable=True),
    sa.Column('sugar_per_100g', sa.Float(), nullable=True),
    sa.Column('sodium_mg_per_100g', sa.Float(), nullable=True),
    sa.Column('is_golden', sa.Boolean(), nullable=True),
    sa.Column('popularity_score', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('fdc_id', sa.String(length=50), nullable=True),
    sa.Column('serving_description', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredients_fdc_id'), 'ingredients', ['fdc_id'], unique=False)
    op.create_index(op.f('ix_ingredients_id'), 'ingredients', ['id'], unique=False)
    op.create_index(op.f('ix_ingredients_is_golden'), 'ingredients', ['is_golden'], unique=False)
    op.create_index(op.f('ix_ingredients_name'), 'ingredients', ['name'], unique=False)
    op.create_index(op.f('ix_ingredients_name_ar'), 'ingredients', ['name_ar'], unique=False)
    op.create_index(op.f('ix_ingredients_popularity_score'), 'ingredients', ['popularity_score'], unique=False)
    op.create_table('user_supplement_stack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('supplement_id', sa.Integer(), nullable=False),
    sa.Column('custom_dosage_amount', sa.Float(), nullable=False),
    sa.Column('time_of_day', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['supplement_id'], ['supplement_catalog.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_supplement_stack_id'), 'user_supplement_stack', ['id'], unique=False)
    op.create_index(op.f('ix_user_supplement_stack_is_active'), 'user_supplement_stack', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_supplement_stack_user_id'), 'user_supplement_stack', ['user_id'], unique=False)
    op.create_table('daily_supplement_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_supplement_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_taken', sa.Boolean(), nullable=True),
    sa.Column('taken_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_supplement_id'], ['user_supplement_stack.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_supplement_log_date'), 'daily_supplement_log', ['date'], unique=False)
    op.create_index(op.f('ix_daily_supplement_log_id'), 'daily_supplement_log', ['id'], unique=False)
    op.create_index(op.f('ix_daily_supplement_log_user_id'), 'daily_supplement_log', ['user_id'], unique=False)
    op.create_table('meals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_log_id', sa.Integer(), nullable=False),
    sa.Column('meal_type', sa.String(length=50), nullable=False),
    sa.Column('time_logged', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['daily_log_id'], ['daily_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meals_daily_log_id'), 'meals', ['daily_log_id'], unique=False)
    op.create_index(op.f('ix_meals_id'), 'meals', ['id'], unique=False)
    op.create_index(op.f('ix_meals_meal_type'), 'meals', ['meal_type'], unique=False)
    op.create_index(op.f('ix_meals_time_logged'), 'meals', ['time_logged'], unique=False)
    op.create_table('meal_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('serving_size_g', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_ingredients_id'), 'meal_ingredients', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meal_ingredients_id'), table_name='meal_ingredients')
    op.drop_table('meal_ingredients')
    op.drop_index(op.f('ix_meals_time_logged'), table_name='meals')
    op.drop_index(op.f('ix_meals_meal_type'), table_name='meals')
    op.drop_index(op.f('ix_meals_id'), table_name='meals')
    op.drop_index(op.f('ix_meals_daily_log_id'), table_name='meals')
    op.drop_table('meals')
    op.drop_index(op.f('ix_daily_supplement_log_user_id'), table_name='daily_supplement_log')
    op.drop_index(op.f('ix_daily_supplement_log_id'), table_name='daily_supplement_log')
    op.drop_index(op.f('ix_daily_supplement_log_date'), table_name='daily_supplement_log')
    op.drop_table('daily_supplement_log')
    op.drop_index(op.f('ix_user_supplement_stack_user_id'), table_name='user_supplement_stack')
    op.drop_index(op.f('ix_user_supplement_stack_is_active'), table_name='user_supplement_stack')
    op.drop_index(op.f('ix_user_supplement_stack_id'), table_name='user_supplement_stack')
    op.drop_table('user_supplement_stack')
    op.drop_index(op.f('ix_ingredients_popularity_score'), table_name='ingredients')
    op.drop_index(op.f('ix_ingredients_name_ar'), table_name='ingredients')
    op.drop_index(op.f('ix_ingredients_name'), table_name='ingredients')
    op.drop_index(op.f('ix_ingredients_is_golden'), table_name='ingredients')
    op.drop_index(op.f('ix_ingredients_id'), table_name='ingredients')
    op.drop_index(op.f('ix_ingredients_fdc_id'), table_name='ingredients')
    op.drop_table('ingredients')
    op.drop_index(op.f('ix_daily_logs_user_id'), table_name='daily_logs')
    op.drop_index(op.f('ix_daily_logs_is_refeed_day'), table_name='daily_logs')
    op.drop_index(op.f('ix_daily_logs_id'), table_name='daily_logs')
    op.drop_index(op.f('ix_daily_logs_date'), table_name='daily_logs')
    op.drop_table('daily_logs')
    op.drop_index(op.f('ix_chat_history_user_id'), table_name='chat_history')
    op.drop_index(op.f('ix_chat_history_id'), table_name='chat_history')
    op.drop_table('chat_history')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_supplement_catalog_id'), table_name='supplement_catalog')
    op.drop_table('supplement_catalog')
    # ### end Alembic commands ###
