"""add supplement tables

Revision ID: 76887d4b4d5f
Revises: cb84a872b7b0
Create Date: 2026-03-24 15:16:17.847951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '76887d4b4d5f'
down_revision: Union[str, None] = 'cb84a872b7b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplement_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('standard_dosage', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('target_goal', sa.String(length=20), nullable=True),
    sa.Column('benefits', sa.Text(), nullable=True),
    sa.Column('recommended_for_activity', sa.String(length=50), nullable=True),
    sa.Column('is_global', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_supplement_catalog_id'), 'supplement_catalog', ['id'], unique=False)
    op.create_table('user_supplement_stack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('supplement_id', sa.Integer(), nullable=False),
    sa.Column('custom_dosage_amount', sa.Float(), nullable=False),
    sa.Column('time_of_day', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['supplement_id'], ['supplement_catalog.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_supplement_stack_id'), 'user_supplement_stack', ['id'], unique=False)
    op.create_index(op.f('ix_user_supplement_stack_is_active'), 'user_supplement_stack', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_supplement_stack_user_id'), 'user_supplement_stack', ['user_id'], unique=False)
    op.create_table('daily_supplement_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_supplement_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_taken', sa.Boolean(), nullable=True),
    sa.Column('taken_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_supplement_id'], ['user_supplement_stack.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_supplement_log_date'), 'daily_supplement_log', ['date'], unique=False)
    op.create_index(op.f('ix_daily_supplement_log_id'), 'daily_supplement_log', ['id'], unique=False)
    op.create_index(op.f('ix_daily_supplement_log_user_id'), 'daily_supplement_log', ['user_id'], unique=False)
    op.drop_index('ix_supplements_id', table_name='supplements')
    op.drop_table('supplements')
    op.drop_index('ix_user_supplements_id', table_name='user_supplements')
    op.drop_table('user_supplements')
    op.create_index(op.f('ix_daily_logs_is_refeed_day'), 'daily_logs', ['is_refeed_day'], unique=False)
    op.create_index(op.f('ix_daily_logs_user_id'), 'daily_logs', ['user_id'], unique=False)
    op.drop_index('ix_ingredients_pop_score', table_name='ingredients')
    op.create_index(op.f('ix_ingredients_popularity_score'), 'ingredients', ['popularity_score'], unique=False)
    op.create_index(op.f('ix_meals_daily_log_id'), 'meals', ['daily_log_id'], unique=False)
    op.create_index(op.f('ix_meals_meal_type'), 'meals', ['meal_type'], unique=False)
    op.create_index(op.f('ix_meals_time_logged'), 'meals', ['time_logged'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meals_time_logged'), table_name='meals')
    op.drop_index(op.f('ix_meals_meal_type'), table_name='meals')
    op.drop_index(op.f('ix_meals_daily_log_id'), table_name='meals')
    op.drop_index(op.f('ix_ingredients_popularity_score'), table_name='ingredients')
    op.create_index('ix_ingredients_pop_score', 'ingredients', ['popularity_score'], unique=False)
    op.drop_index(op.f('ix_daily_logs_user_id'), table_name='daily_logs')
    op.drop_index(op.f('ix_daily_logs_is_refeed_day'), table_name='daily_logs')
    op.create_table('user_supplements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('supplement_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('dosage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('unit', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_supplements_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_supplements_pkey')
    )
    op.create_index('ix_user_supplements_id', 'user_supplements', ['id'], unique=False)
    op.create_table('supplements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('default_daily_dose', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_global', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='supplements_pkey')
    )
    op.create_index('ix_supplements_id', 'supplements', ['id'], unique=False)
    op.drop_index(op.f('ix_daily_supplement_log_user_id'), table_name='daily_supplement_log')
    op.drop_index(op.f('ix_daily_supplement_log_id'), table_name='daily_supplement_log')
    op.drop_index(op.f('ix_daily_supplement_log_date'), table_name='daily_supplement_log')
    op.drop_table('daily_supplement_log')
    op.drop_index(op.f('ix_user_supplement_stack_user_id'), table_name='user_supplement_stack')
    op.drop_index(op.f('ix_user_supplement_stack_is_active'), table_name='user_supplement_stack')
    op.drop_index(op.f('ix_user_supplement_stack_id'), table_name='user_supplement_stack')
    op.drop_table('user_supplement_stack')
    op.drop_index(op.f('ix_supplement_catalog_id'), table_name='supplement_catalog')
    op.drop_table('supplement_catalog')
    # ### end Alembic commands ###
