"""initial migration

Revision ID: cb84a872b7b0
Revises: 
Create Date: 2026-03-24 13:48:34.638846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb84a872b7b0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_daily_logs_is_refeed_day'), 'daily_logs', ['is_refeed_day'], unique=False)
    op.create_index(op.f('ix_daily_logs_user_id'), 'daily_logs', ['user_id'], unique=False)
    op.drop_index('ix_ingredients_pop_score', table_name='ingredients')
    op.create_index(op.f('ix_ingredients_popularity_score'), 'ingredients', ['popularity_score'], unique=False)
    op.create_index(op.f('ix_meals_daily_log_id'), 'meals', ['daily_log_id'], unique=False)
    op.create_index(op.f('ix_meals_meal_type'), 'meals', ['meal_type'], unique=False)
    op.create_index(op.f('ix_meals_time_logged'), 'meals', ['time_logged'], unique=False)
    op.create_index(op.f('ix_user_supplements_is_active'), 'user_supplements', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_supplements_user_id'), 'user_supplements', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_supplements_user_id'), table_name='user_supplements')
    op.drop_index(op.f('ix_user_supplements_is_active'), table_name='user_supplements')
    op.drop_index(op.f('ix_meals_time_logged'), table_name='meals')
    op.drop_index(op.f('ix_meals_meal_type'), table_name='meals')
    op.drop_index(op.f('ix_meals_daily_log_id'), table_name='meals')
    op.drop_index(op.f('ix_ingredients_popularity_score'), table_name='ingredients')
    op.create_index('ix_ingredients_pop_score', 'ingredients', ['popularity_score'], unique=False)
    op.drop_index(op.f('ix_daily_logs_user_id'), table_name='daily_logs')
    op.drop_index(op.f('ix_daily_logs_is_refeed_day'), table_name='daily_logs')
    # ### end Alembic commands ###
